baseurl = "https://jarrodoverson.com/"
title = "Jarrod Overson"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-22728809-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  description = "Describe your website" # meta description
  author = "Jarrod Overson"
  authorLink = "https://jarrodoverson.com/"
  bio = [
    "Jarrod is a Director at Shape Security, speaker, O'Reilly author."
  ]
  copyright = [
    "&copy; Jarrod Overson",
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "jsoverson@gmail.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3

  [[menu.main]]
  name = "Speaking"
  url = "speaking/"
  weight = 4

  [params.social]
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "jsoverson@gmail.com"
  twitter       = "https://twitter.com/jsoverson"
  linkedin      = "https://www.linkedin.com/in/jsoverson/"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github        = "https://github.com/jsoverson"
  #pinterest     = "full profile url in pinterest"
  rss           = true